---
name: Rebuild Devcontainer to Update Dependencies

permissions:
  packages: write
  contents: write

on:
  schedule:
    - cron: '0 4 1 * *' # Run monthly on the 1st at 4 AM UTC
  workflow_dispatch:

jobs:
  rebuild-devcontainer:
    name: Rebuild devcontainer base image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: version
        run: |
          VERSION=$(date +%y.%m.%d.%H.%M)
          echo "tag=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build and push devcontainer image
        uses: docker/build-push-action@v5
        with:
          context: ./.devcontainer
          platforms: linux/amd64,linux/arm64
          push: true
          no-cache: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/api-devcontainer:${{ steps.version.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/api-devcontainer:latest
